name: rhemabiblequiz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
  # sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  logging: ^1.2.0
  go_router: ^12.1.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^3.1.0
  audioplayers: ^5.2.0
  # 5.0.0
  # audioplayers: ^4.0.0
  # games_services: ^4.0.0
  animated_text_kit: ^4.2.2
  collection: ^1.17.2
  lottie: ^2.7.0
  animator: ^3.3.0
  circular_progress_bar_with_lines: ^0.0.7
  # just_audio: ^0.9.36
  # firebase_crashlytics: ^3.4.3
  # firebase_core: ^2.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
flutter _icons:
  android: "launcher_icon"
  iso: "launcher_icon"
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png" 


flutter:
  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/images/boob.png
    - assets/images/app_icon.png
    # - shorebird.yaml
    # reward animation
    - assets/animation/lmcmpxt3.json
    # blinking star small 2
    - assets/animation/lmcmqh5q.json
    # blinking star small
    - assets/animation/lmcmqh5qy.json
    # green blue and yellow ball animation juggling animation 2
    - assets/animation/lmcmrpc6.json
    # cup winner animation 2
    - assets/animation/lmcn1iah.json
    # cup winner animation
    - assets/animation/lmcn1iz9.json
    # red rotating circle animation
    - assets/animation/lmcn2hgh.json
    # angle celebration
    - assets/animation/lmcn6bsp.json
    # green blue and yellow ball animation juggling animation
    - assets/animation/lmcn06lm.json
    # good animation (green)
    - assets/animation/lmcn6zkf.json
    # celeberation animation
    - assets/animation/lmcn9dni.json
    # rotaing balls
    - assets/animation/lmcn446j.json
    # center celebration
    - assets/animation/animation_lmcn9dni.json
    # mobile cloud or horse racing
    - assets/animation/animation_lme0ppva.json
    # wrong answer
    - assets/animation/animation_lme1emfg.json

  uses-material-design: true
  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/font/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: LuckiestGuy-Regular
      fonts:
        - asset: assets/font/LuckiestGuy-Regular.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
